### ISSUE TITLE
Add VERSION and release new version

### ISSUE THREAD

**Issue by k-bx** [timedata-org/streamy#8]
Hi, current version fails with:

```
$ pip3 install Streamy
Collecting Streamy
  Using cached streamy-2.0.3.tar.gz (1.5 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-724cbfrc/Streamy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-724cbfrc/Streamy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-724cbfrc/Streamy/pip-egg-info
         cwd: /tmp/pip-install-724cbfrc/Streamy/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-724cbfrc/Streamy/setup.py", line 26, in <module>
        VERSION = open(FILENAME).read().strip()
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-724cbfrc/Streamy/VERSION'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by rec** [comment]
Hello!  Sorry for the delay.  I'll get on this tomorrow AM!

**Comment by k-bx** [comment]
No problem. The bigger issue for me was performance, I ended up using `jq` to turn a one-line json stream into a line-per-object one (`jq -c . all_events.json > all_events-02.json`), otherwise it was too slow unfortunately.

**Comment by rec** [comment]
To be honest, since I wrote this, I too have moved entirely to "one line per object", which is just much more convenient!  But I'll fix this issue when I've done my coffee, just to get it done.

**Comment by rec** [comment]
Well, uch, I pushed a version that fixes this error, but it seems that I have two forks of this that have diverged and I don't have time to see what the difference is.

Tempted to just deprecate the whole thing... luckily, I have many more much more interesting projects these days.  https://github.com/rec/
